### ISSUE TITLE
Installing components fails

### ISSUE THREAD

**Issue by andybak** [ngokevin/angle#3]
I tried the instructions in the readme (MacOS 10.11.6)

    aframe$ angle initscene
    Initializing A-Frame scene
    ? What is your scene's title? (e.g., Forest Scene) Ixxy Test
    ? Do you want tracked controls with hand models? No
    aframe$ cd ixxy-test/
    aframe/ixxy-test$ angle install aframe-mountain-component
    Installing A-Frame component `aframe-mountain-component` to `index.html`
    Detected A-Frame version 0.3.2
    /usr/local/lib/node_modules/angle/lib/install.js:49
      if (moduleName in registry[version].components) {
                                         ^

    TypeError: Cannot read property 'components' of undefined
        at Command.install (/usr/local/lib/node_modules/angle/lib/install.js:49:38)
        at Command.listener (/usr/local/lib/node_modules/angle/node_modules/commander/index.js:301:8)
        at emitTwo (events.js:106:13)
        at Command.emit (events.js:191:7)
        at Command.parseArgs (/usr/local/lib/node_modules/angle/node_modules/commander/index.js:615:12)
        at Command.parse (/usr/local/lib/node_modules/angle/node_modules/commander/index.js:458:21)
        at Object.<anonymous> (/usr/local/lib/node_modules/angle/index.js:23:9)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)

**Comment by ngokevin** [comment]
Fixed, thanks!

**Comment by ngokevin** [comment]
https://github.com/ngokevin/angle/commit/4db79c0155477b72cbe045bf1673d61c55aa9b23
