### ISSUE TITLE
Install layout component failed.

### ISSUE THREAD

**Issue by perrychen901105** [ngokevin/angle#41]
I follow the tutorial https://aframe.io/docs/0.7.0/guides/building-a-360-image-gallery.html# to install the layout and other components, but when I use angle to install the related components, it gives me below errors:

> Installing A-Frame component `layout` to `index.html`
Detected A-Frame version 0.7.0
/Users/pchen143/.nvm/versions/node/v8.9.1/lib/node_modules/angle/lib/install.js:57
  if (moduleName in registry[version].components) {
                                      ^

>TypeError: Cannot read property 'components' of undefined
    at Command.install (/Users/pchen143/.nvm/versions/node/v8.9.1/lib/node_modules/angle/lib/install.js:57:39)
    at Command.listener (/Users/pchen143/.nvm/versions/node/v8.9.1/lib/node_modules/angle/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (/Users/pchen143/.nvm/versions/node/v8.9.1/lib/node_modules/angle/node_modules/commander/index.js:653:12)
    at Command.parse (/Users/pchen143/.nvm/versions/node/v8.9.1/lib/node_modules/angle/node_modules/commander/index.js:475:21)
    at Object.<anonymous> (/Users/pchen143/.nvm/versions/node/v8.9.1/lib/node_modules/angle/index.js:27:4)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)

I use the command 'npm uninstall -g angle' and 'angle install layout'. My node version is 8.9.1.

**Comment by danorak** [comment]
I have exactly the same issue - anyone have any idea what the issue is?

**Comment by technotherion** [comment]
I've noted that angle seems to have some weird permission errors. Try ```sudo npm install -g angle``` instead.

**Comment by dsinni** [comment]
Same. Can't seem to install any components with `angle install`, up to and including version `0.8.2` (thanks for updating the A-Frame version).

I've tried the following formats with multiple components to no avail:

- `angle install aframe-extras`
- `angle install aframe-extras index.html`

Thanks.
