### ISSUE TITLE
Cannot find module 'aframe-registry'

### ISSUE THREAD

**Issue by damienstanton** [ngokevin/angle#43]
Fresh install in this environment:
npm `6.1.0`
node `10.4.0`
macOS `10.13.5`

Trying to run
```
$ angle initscene
```

Returns the following:
```
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module 'aframe-registry'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/angle/lib/install.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
```

**Comment by davie-robertson** [comment]
same here - with node v8.11.1

**Comment by DaSchTour** [comment]
I guess aframe-registry should be a peerDependency in package.json

**Comment by damienstanton** [comment]
Yep, and someone already has a PR open #44
